php7:
  build: .
  dockerfile: /etc/docker/dockerfile_php_7
  volumes:
    - ./src:/var/www/html
    - ./etc/php:/usr/local/etc/php
  ports:
    - "5000:80"
  links:
    - mysql


mysql:
  image: mysql
  ports:
    - "5506:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=todo_list
  volumes: 
    - ./etc/mysql:/docker-entrypoint-initdb.d
